Update actions.yml

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -53,6 +53,9 @@ jobs:
     - name: Set AKS Context
       run: |
         az aks get-credentials --resource-group actions --name actions --overwrite-existing
+    - name: Delete existing ACR Pull Secret
+      run: |
+        kubectl delete secret acr-secret || echo "Secret not found, continuing..."
     - name: Create ACR Pull Secret in AKS
       run: |
         kubectl create secret docker-registry acr-secret \
